/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditProgressCard: typeof import('./src/components/common/AuditProgressCard.vue')['default']
    CompetitorTable: typeof import('./src/components/dashboard/CompetitorTable.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/common/ErrorState.vue')['default']
    LoadingSkeleton: typeof import('./src/components/common/LoadingSkeleton.vue')['default']
    OnboardingWizard: typeof import('./src/components/common/OnboardingWizard.vue')['default']
    PlatformGrid: typeof import('./src/components/dashboard/PlatformGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreCard: typeof import('./src/components/dashboard/ScoreCard.vue')['default']
    TrendChart: typeof import('./src/components/dashboard/TrendChart.vue')['default']
  }
}
